### PR TITLE
Fix OOBE, update README

### LINKED ISSUE #264: OOBE in `Comparator.checkAlphanumericPrerelease(String, String)`
An ArrayIndexOutOfBoundsException is thrown from `Comparator.checkAlphanumericPrerelease(String, String)` at line 109 if the array created at lines 106-107 is not of length 2 (see screenshot)

It occurs while comparing versions `4.0.0-beta.9-macro` and `4.0.0-beta.9-macro2` from the npm package `styled-components` using `Comparator.compareTo(Semver, Semver)` after coercing those versions with `Semver.coerce(String)`.

CleanShot 2024-06-07 at 20 46 02@2x

### PR DESCRIPTION
**Pull request by WarningImHack3r**
Fixes #264

Return `a.length - b.length` if the regex arrays don't have the same length. This kind of OOB issue seems impossible elsewhere in the file, so it should be fine.

I also updated the README to fix typos and apply the changes IJ suggested, including a TOC fix.

### CODE REVIEW

File: src/main/java/org/semver4j/internal/Comparator.java [hunk 1]
```diff
@@ -105,6 +105,9 @@ private static int compareIdentifiers(@NotNull final String a, @NotNull final St
     private static Integer checkAlphanumericPrerelease(@NotNull final String a, @NotNull final String b) {
         String[] tokenArrA = a.split(TRAILING_DIGITS_EXTRACT);
         String[] tokenArrB = b.split(TRAILING_DIGITS_EXTRACT);
+        if (tokenArrA.length != tokenArrB.length) {
+            return tokenArrA.length - tokenArrB.length;
```
Comment (piotrooo) [inline src/main/java/org/semver4j/internal/Comparator.java:109]: Could you add an appropriate test for this case?

**Review by piotrooo — CHANGES_REQUESTED** [review]

File: src/main/java/org/semver4j/internal/Comparator.java (hunk 1 above)
Comment (WarningImHack3r) [reply src/main/java/org/semver4j/internal/Comparator.java:109]: Yep I was thinking about that but I didn't see this class in the test package so I didn't do any
But I'll definitely add that

**Review by piotrooo — APPROVED** [review]

**Comment by piotrooo** [comment]
Many thanks for your contribution :pray:
